stages:
   - build
   - deploy

# build stage
build_app:
   image: node:alpine
   stage: build
   only:
      - master
   tags:
      - production
   script:
      - npm install
      - npm run build
   cache:
     paths:
       - node_modules/ 
   artifacts:
      paths:
         # build folder
         - dist/
      expire_in: 1 hour

# production stage
production:
   stage: deploy
   only:
      - master
   tags:
      - production
   script:
       cp -r dist/* /var/www/html/